repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: .venv/Scripts/python.exe
        args: ["-m", "ruff", "check", ".", "--fix"]
        language: system
        pass_filenames: false

      - id: black
        name: black
        entry: .venv/Scripts/python.exe
        args: ["-m", "black", "."]
        language: system
        pass_filenames: false
        exclude: '^(legacy/|code\.py$)'

      - id: isort
        name: isort
        entry: .venv/Scripts/python.exe
        args: ["-m", "isort", "."]
        language: system
        pass_filenames: false
