name: Python checks (soft)
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt || true
      - name: Lint (non-blocking)
        run: |
          pip install black isort flake8
          echo "::group::Black diff"; black --diff --quiet . || true; echo "::endgroup::"
          echo "::group::isort diff"; isort --diff . || true; echo "::endgroup::"
          echo "::group::flake8"; flake8 . || true; echo "::endgroup::"
